#!/usr/bin/env node

var
	argv=require("yargs")
		.version()
		.usage("Usage:\n  $0 [input filename] [output filename] -f [filter]\n  $0 < [input] > [output] -f [filter] -t")
		.example("$0 oecd.json oecd-subset.json -f \"area\"=\"DE\",\"year\"=\"2014\"", "converts JSON-stat file oecd.json into a new JSON-stat file (oecd-subset.json).")
		.example("$0 < oecd.json > oecd-subset.json -f \"area\"=\"DE\",\"year\"=\"2014\" -t", "converts JSON-stat stream oecd.json into a new JSON-stat stream (oecd-subset.json).")
		.alias("f", "filter")
		.describe("f", "Filter string (for example: area=DE,year=2014)")
		.boolean("t")
		.alias("t", "stream")
		.describe("t", "Enable the stream interface")
		.help("h")
		.alias("h", "help")
		.argv
	,
	inout=require("./inout"),

	callback=function(contents){
		var
			arrfil,
			subset,
			filter=argv.filter
		;

		//filter is not required: if not specified (no -f or -f without string) input=output
		if(!filter || filter===true){
			return contents;
		}

		if(filter.indexOf("=")===-1){
			console.error("Error: The filter has not been specified correctly (missing =).");
			process.exit(1);
		}

		arrfil=filter.split(",").map(function(e){
			return e.split("=");
		});

		subset=inout.dataset(contents).Slice(arrfil);
		if(subset===null){
			console.error("Error: The input does not containt valid JSON-stat or the filters are not valid.");
			process.exit(1);
		}else{
			return JSON.stringify(subset.__tree__);
		}
	}
;

inout.main(argv, callback, true);
